# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  netcoreteste:
    image: netcoreteste
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    networks:
      - rabbitmq_go_net
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 8080:15672
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge